
var A0 = {name:"Kentucky Brunch Brand Stout",brewloc:"Toppling Goliath Brewing Company",style:"American Double / Imperial Stout",rank:1}
var A1 = {name:"Heady Topper",brewloc:"The Alchemist Brewery and Visitors Center",style:"American Double / Imperial IPA",rank:2}
var A2 = {name:"Barrel-Aged Abraxas",brewloc:"Perennial Artisan Ales",style:"American Double / Imperial Stout",rank:3}
var A3 = {name:"Marshmallow Handjee",brewloc:"3 Floyds Brewing Co.",style:"Russian Imperial Stout",rank:4}
var A4 = {name:"Hunahpu's Imperial Stout - Double Barrel Aged",brewloc:"Cigar City Brewing",style:"American Double / Imperial Stout",rank:5}
var A5 = {name:"King Julius",brewloc:"Tree House Brewing Company",style:"American Double / Imperial IPA",rank:6}
var A6 = {name:"Pliny The Younger",brewloc:"Russian River Brewing Company",style:"American Double / Imperial IPA",rank:7}
var A7 = {name:"Fundamental Observation",brewloc:"Bottle Logic Brewing",style:"American Double / Imperial Stout",rank:8}
var A8 = {name:"Very Hazy",brewloc:"Tree House Brewing Company",style:"American Double / Imperial IPA",rank:9}
var A9 = {name:"Mornin' Delight",brewloc:"Toppling Goliath Brewing Company",style:"American Double / Imperial Stout",rank:10}
var A10 = {name:"Bourbon County Brand Coffee Stout",brewloc:"Goose Island Beer Co.",style:"American Double / Imperial Stout",rank:11}
var A11 = {name:"CBS (Canadian Breakfast Stout)",brewloc:"Founders Brewing Company",style:"American Double / Imperial Stout",rank:12}
var A12 = {name:"Julius",brewloc:"Tree House Brewing Company",style:"American IPA",rank:13}
var A13 = {name:"Pliny The Elder",brewloc:"Russian River Brewing Company",style:"American Double / Imperial IPA",rank:14}
var A14 = {name:"Juice Machine",brewloc:"Tree House Brewing Company",style:"American Double / Imperial IPA",rank:15}
var A15 = {name:"Very Green",brewloc:"Tree House Brewing Company",style:"American Double / Imperial IPA",rank:16}
var A16 = {name:"Double Sunshine IPA",brewloc:"Lawson's Finest Liquids",style:"American Double / Imperial IPA",rank:17}
var A17 = {name:"Cantillon Fou' Foune",brewloc:"Brasserie Cantillon",style:"Lambic - Fruit",rank:18}
var A18 = {name:"SR-71",brewloc:"Toppling Goliath Brewing Company",style:"American Double / Imperial Stout",rank:19}
var A19 = {name:"Doubleganger",brewloc:"Tree House Brewing Company",style:"American Double / Imperial IPA",rank:20}
var A20 = {name:"Dinner",brewloc:"Maine Beer Company",style:"American Double / Imperial IPA",rank:21}
var A21 = {name:"Assassin",brewloc:"Toppling Goliath Brewing Company",style:"American Double / Imperial Stout",rank:22}
var A22 = {name:"Speedway Stout - Vietnamese Coffee - Bourbon-Barrel Aged",brewloc:"AleSmith Brewing Company",style:"American Double / Imperial Stout",rank:23}
var A23 = {name:"Morning Wood",brewloc:"Funky Buddha Brewery",style:"American Porter",rank:24}
var A24 = {name:"Abner",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial IPA",rank:25}
var A25 = {name:"Parabola",brewloc:"Firestone Walker Brewing Co.",style:"Russian Imperial Stout",rank:26}
var A26 = {name:"King Sue",brewloc:"Toppling Goliath Brewing Company",style:"American Double / Imperial IPA",rank:27}
var A27 = {name:"Duck Duck Gooze",brewloc:"The Lost Abbey",style:"Gueuze",rank:28}
var A28 = {name:"Triple Sunshine IPA",brewloc:"Lawson's Finest Liquids",style:"American Double / Imperial IPA",rank:29}
var A29 = {name:"Cantillon Lou Pepe - Kriek",brewloc:"Brasserie Cantillon",style:"Lambic - Fruit",rank:30}
var A30 = {name:"KBS (Kentucky Breakfast Stout)",brewloc:"Founders Brewing Company",style:"American Double / Imperial Stout",rank:31}
var A31 = {name:"Bourbon County Brand Stout",brewloc:"Goose Island Beer Co.",style:"American Double / Imperial Stout",rank:32}
var A32 = {name:"Trappist Westvleteren 12 (XII)",brewloc:"Brouwerij Westvleteren (Sint-Sixtusabdij van Westvleteren)",style:"Quadrupel (Quad)",rank:33}
var A33 = {name:"Drie Fonteinen Zenne Y Frontera",brewloc:"Brouwerij 3 Fonteinen",style:"Lambic - Unblended",rank:34}
var A34 = {name:"Double Citra",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial IPA",rank:35}
var A35 = {name:"Zombie Dust",brewloc:"3 Floyds Brewing Co.",style:"American Pale Ale (APA)",rank:36}
var A36 = {name:"Fuzzy",brewloc:"Side Project Brewing",style:"American Wild Ale",rank:37}
var A37 = {name:"Green",brewloc:"Tree House Brewing Company",style:"American IPA",rank:38}
var A38 = {name:"Double Galaxy",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial IPA",rank:39}
var A39 = {name:"Double Dry Hopped Congress Street",brewloc:"Trillium Brewing Company",style:"American IPA",rank:40}
var A40 = {name:"Sip Of Sunshine IPA",brewloc:"Lawson's Finest Liquids",style:"American Double / Imperial IPA",rank:41}
var A41 = {name:"Atrial Rubicite",brewloc:"Jester King Brewery",style:"American Wild Ale",rank:42}
var A42 = {name:"Focal Banger",brewloc:"The Alchemist Brewery and Visitors Center",style:"American IPA",rank:43}
var A43 = {name:"Westly",brewloc:"Sante Adairius Rustic Ales",style:"American Wild Ale",rank:44}
var A44 = {name:"Doppelganger",brewloc:"Tree House Brewing Company",style:"American Double / Imperial IPA",rank:45}
var A45 = {name:"Double Dry Hopped Fort Point Pale Ale",brewloc:"Trillium Brewing Company",style:"American Pale Ale (APA)",rank:46}
var A46 = {name:"Haze",brewloc:"Tree House Brewing Company",style:"American Double / Imperial IPA",rank:47}
var A47 = {name:"Society & Solitude #4",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial IPA",rank:48}
var A48 = {name:"Hunahpu's Imperial Stout",brewloc:"Cigar City Brewing",style:"American Double / Imperial Stout",rank:49}
var A49 = {name:"Swish",brewloc:"Bissell Brothers Brewing Co.",style:"American Double / Imperial IPA",rank:50}
var A50 = {name:"Headroom",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:51}
var A51 = {name:"Cantillon Lou Pepe - Framboise",brewloc:"Brasserie Cantillon",style:"Lambic - Fruit",rank:52}
var A52 = {name:"Supplication",brewloc:"Russian River Brewing Company",style:"American Wild Ale",rank:53}
var A53 = {name:"Cable Car",brewloc:"The Lost Abbey",style:"American Wild Ale",rank:54}
var A54 = {name:"Nectarine Premiere",brewloc:"de Garde Brewing",style:"Saison / Farmhouse Ale",rank:55}
var A55 = {name:"Pseudo Sue - Double Dry-Hopped",brewloc:"Toppling Goliath Brewing Company",style:"American Pale Ale (APA)",rank:56}
var A56 = {name:"Aaron",brewloc:"Hill Farmstead Brewery",style:"English Barleywine",rank:57}
var A57 = {name:"Citra",brewloc:"Kern River Brewing Company",style:"American Double / Imperial IPA",rank:58}
var A58 = {name:"Galaxy Dry Hopped Fort Point Pale Ale",brewloc:"Trillium Brewing Company",style:"American Pale Ale (APA)",rank:59}
var A59 = {name:"West Ashley",brewloc:"Sante Adairius Rustic Ales",style:"American Wild Ale",rank:60}
var A60 = {name:"Barrel Aged Imperial German Chocolate Cupcake Stout",brewloc:"Angry Chair Brewing",style:"American Double / Imperial Stout",rank:61}
var A61 = {name:"Grande Negro Voodoo Papi - Bourbon Barrel Aged",brewloc:"Voodoo Brewery",style:"American Double / Imperial Stout",rank:62}
var A62 = {name:"Beatification",brewloc:"Russian River Brewing Company",style:"American Wild Ale",rank:63}
var A63 = {name:"Coffee Cinnamon B-Bomb",brewloc:"Fremont Brewing Company",style:"Winter Warmer",rank:64}
var A64 = {name:"Alter Ego",brewloc:"Tree House Brewing Company",style:"American IPA",rank:65}
var A65 = {name:"Fourth Dementia - Bourbon Barrel-Aged",brewloc:"Kuhnhenn Brewing Company",style:"Old Ale",rank:66}
var A66 = {name:"Bourbon Paradise",brewloc:"Prairie Artisan Ales",style:"American Double / Imperial Stout",rank:67}
var A67 = {name:"Black Note Stout",brewloc:"Bell's Brewery - Eccentric Café & General Store",style:"American Double / Imperial Stout",rank:68}
var A68 = {name:"Black Tuesday",brewloc:"The Bruery",style:"American Double / Imperial Stout",rank:69}
var A69 = {name:"Ann",brewloc:"Hill Farmstead Brewery",style:"Saison / Farmhouse Ale",rank:70}
var A70 = {name:"Ephraim",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial IPA",rank:71}
var A71 = {name:"Drie Fonteinen Oude Geuze Vintage",brewloc:"Brouwerij 3 Fonteinen",style:"Gueuze",rank:72}
var A72 = {name:"Society & Solitude #5",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial IPA",rank:73}
var A73 = {name:"Saison Du Fermier",brewloc:"Side Project Brewing",style:"Saison / Farmhouse Ale",rank:74}
var A74 = {name:"Triple Shot",brewloc:"Tree House Brewing Company",style:"American Double / Imperial Stout",rank:75}
var A75 = {name:"Chocolate Rain",brewloc:"The Bruery",style:"American Double / Imperial Stout",rank:76}
var A76 = {name:"Beer Geek Vanilla Shake - Bourbon Barrel-Aged",brewloc:"Mikkeller ApS",style:"American Double / Imperial Stout",rank:77}
var A77 = {name:"Bourbon Barrel Aged Dark Lord Imperial Stout",brewloc:"3 Floyds Brewing Co.",style:"Russian Imperial Stout",rank:78}
var A78 = {name:"Cantillon Saint Lamvinus",brewloc:"Brasserie Cantillon",style:"Lambic - Fruit",rank:79}
var A79 = {name:"In Perpetuity",brewloc:"Tree House Brewing Company",style:"American IPA",rank:80}
var A80 = {name:"Dark Horse Bourbon Barrel Aged Plead The 5th",brewloc:"Dark Horse Brewing Company",style:"Russian Imperial Stout",rank:81}
var A81 = {name:"Sunday Brunch",brewloc:"Kane Brewing Company",style:"American Porter",rank:82}
var A82 = {name:"Double Shot",brewloc:"Tree House Brewing Company",style:"American Stout",rank:83}
var A83 = {name:"Keene Idea",brewloc:"Alpine Beer Company",style:"American Double / Imperial IPA",rank:84}
var A84 = {name:"Cutting Tiles (Mosaic)",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:85}
var A85 = {name:"§ucaba",brewloc:"Firestone Walker Brewing Co.",style:"English Barleywine",rank:86}
var A86 = {name:"Notorious Triple IPA",brewloc:"Boneyard Beer Company",style:"American Double / Imperial IPA",rank:87}
var A87 = {name:"Pseudo Sue",brewloc:"Toppling Goliath Brewing Company",style:"American Pale Ale (APA)",rank:88}
var A88 = {name:"Beyond Good And Evil",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial Stout",rank:89}
var A89 = {name:"Last Buffalo In The Park",brewloc:"Funky Buddha Brewery",style:"American Porter",rank:90}
var A90 = {name:"Breakfast Stout",brewloc:"Founders Brewing Company",style:"American Double / Imperial Stout",rank:91}
var A91 = {name:"Mexican Brunch",brewloc:"Kane Brewing Company",style:"American Porter",rank:92}
var A92 = {name:"Pirate Bomb!",brewloc:"Prairie Artisan Ales",style:"American Double / Imperial Stout",rank:93}
var A93 = {name:"Abricot Du Fermier",brewloc:"Side Project Brewing",style:"Saison / Farmhouse Ale",rank:94}
var A94 = {name:"Speedway Stout - Bourbon Barrel-Aged",brewloc:"AleSmith Brewing Company",style:"American Double / Imperial Stout",rank:95}
var A95 = {name:"Parabajava",brewloc:"Firestone Walker Brewing Co.",style:"Russian Imperial Stout",rank:96}
var A96 = {name:"Bourbon County Brand Barleywine Ale",brewloc:"Goose Island Beer Co.",style:"English Barleywine",rank:97}
var A97 = {name:"Miami Madness",brewloc:"J. Wakefield Brewing",style:"Berliner Weissbier",rank:98}
var A98 = {name:"The Rusty Nail",brewloc:"Fremont Brewing Company",style:"American Double / Imperial Stout",rank:99}
var A99 = {name:"Grey Monday",brewloc:"The Bruery",style:"American Double / Imperial Stout",rank:100}
var A100 = {name:"Double Dry Hopped Double Mosaic Dream",brewloc:"Other Half Brewing Co.",style:"American Double / Imperial IPA",rank:101}
var A101 = {name:"The Broken Truck",brewloc:"de Garde Brewing",style:"American Wild Ale",rank:102}
var A102 = {name:"Wide Awake It's Morning",brewloc:"Funky Buddha Brewery",style:"American Porter",rank:103}
var A103 = {name:"Trappistes Rochefort 10",brewloc:"Brasserie de Rochefort",style:"Quadrupel (Quad)",rank:104}
var A104 = {name:"Flora Plum",brewloc:"Hill Farmstead Brewery",style:"Saison / Farmhouse Ale",rank:105}
var A105 = {name:"Bomb!",brewloc:"Prairie Artisan Ales",style:"American Double / Imperial Stout",rank:106}
var A106 = {name:"Pugachev Royale",brewloc:"Hangar 24 Brewing",style:"Russian Imperial Stout",rank:107}
var A107 = {name:"Abrasive Ale",brewloc:"Surly Brewing Company",style:"American Double / Imperial IPA",rank:108}
var A108 = {name:"Scaled Way Up",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:109}
var A109 = {name:"A Deal With The Devil",brewloc:"Anchorage Brewing Company",style:"American Barleywine",rank:110}
var A110 = {name:"Imperial Biscotti Break - Bourbon Barrel-Aged",brewloc:"Evil Twin Brewing",style:"American Double / Imperial Stout",rank:111}
var A111 = {name:"Permanent Funeral",brewloc:"3 Floyds Brewing Co.",style:"American Double / Imperial IPA",rank:112}
var A112 = {name:"Everett Porter",brewloc:"Hill Farmstead Brewery",style:"American Porter",rank:113}
var A113 = {name:"Great",brewloc:"Alpine Beer Company",style:"American Barleywine",rank:114}
var A114 = {name:"Maman",brewloc:"Perennial Artisan Ales",style:"American Double / Imperial Stout",rank:115}
var A115 = {name:"Congress Street IPA",brewloc:"Trillium Brewing Company",style:"American IPA",rank:116}
var A116 = {name:"Society & Solitude #6",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial IPA",rank:117}
var A117 = {name:"Double Dry Hopped Melcher Street",brewloc:"Trillium Brewing Company",style:"American IPA",rank:118}
var A118 = {name:"Mosaic Dry Hopped Fort Point",brewloc:"Trillium Brewing Company",style:"American Pale Ale (APA)",rank:119}
var A119 = {name:"Susan",brewloc:"Hill Farmstead Brewery",style:"American IPA",rank:120}
var A120 = {name:"Cantillon Blåbær Lambik",brewloc:"Brasserie Cantillon",style:"Lambic - Fruit",rank:121}
var A121 = {name:"Speedway Stout - Vietnamese Coffee",brewloc:"AleSmith Brewing Company",style:"American Double / Imperial Stout",rank:122}
var A122 = {name:"Consecration",brewloc:"Russian River Brewing Company",style:"American Wild Ale",rank:123}
var A123 = {name:"Heavy Mettle",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:124}
var A124 = {name:"Montmorency Vs Balaton",brewloc:"Jester King Brewery",style:"American Wild Ale",rank:125}
var A125 = {name:"Sosus",brewloc:"Toppling Goliath Brewing Company",style:"American Double / Imperial IPA",rank:126}
var A126 = {name:"Drie Fonteinen Framboos",brewloc:"Brouwerij 3 Fonteinen",style:"Lambic - Fruit",rank:127}
var A127 = {name:"Bourbon Barrel Aged Dark Star: Coffee Edition",brewloc:"Fremont Brewing Company",style:"American Double / Imperial Stout",rank:128}
var A128 = {name:"Double Dry Hopped Mylar Bags",brewloc:"Other Half Brewing Co.",style:"American Double / Imperial IPA",rank:129}
var A129 = {name:"Saison Bernice",brewloc:"Sante Adairius Rustic Ales",style:"Saison / Farmhouse Ale",rank:130}
var A130 = {name:"Drie Fonteinen Hommage",brewloc:"Brouwerij 3 Fonteinen",style:"Lambic - Fruit",rank:131}
var A131 = {name:"Mocha Wednesday",brewloc:"The Bruery",style:"American Double / Imperial Stout",rank:132}
var A132 = {name:"Upper Case",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:133}
var A133 = {name:"Pirate Paradise",brewloc:"Prairie Artisan Ales",style:"American Double / Imperial Stout",rank:134}
var A134 = {name:"Crusher",brewloc:"The Alchemist Brewery and Visitors Center",style:"American Double / Imperial IPA",rank:135}
var A135 = {name:"Cantillon Lou Pepe - Gueuze",brewloc:"Brasserie Cantillon",style:"Gueuze",rank:136}
var A136 = {name:"Darkness",brewloc:"Surly Brewing Company",style:"Russian Imperial Stout",rank:137}
var A137 = {name:"Cutting Tiles - Galaxy",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:138}
var A138 = {name:"No Rules",brewloc:"Perrin Brewery",style:"American Porter",rank:139}
var A139 = {name:"The Peach",brewloc:"de Garde Brewing",style:"American Wild Ale",rank:140}
var A140 = {name:"Ground State",brewloc:"Bottle Logic Brewing",style:"American Double / Imperial Stout",rank:141}
var A141 = {name:"Barrel Aged Bomb!",brewloc:"Prairie Artisan Ales",style:"American Double / Imperial Stout",rank:142}
var A142 = {name:"The Abyss",brewloc:"Deschutes Brewery",style:"American Double / Imperial Stout",rank:143}
var A143 = {name:"Ten FIDY - Bourbon Barrel Aged",brewloc:"Oskar Blues Grill & Brew",style:"Russian Imperial Stout",rank:144}
var A144 = {name:"Genealogy Of Morals (Bourbon Barrel Aged)",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial Stout",rank:145}
var A145 = {name:"Drie Fonteinen Oude Geuze Golden Blend",brewloc:"Brouwerij 3 Fonteinen",style:"Gueuze",rank:146}
var A146 = {name:"Double Barrel Jesus",brewloc:"Evil Twin Brewing",style:"American Double / Imperial Stout",rank:147}
var A147 = {name:"Prairie Apple Brandy Noir",brewloc:"Prairie Artisan Ales",style:"American Double / Imperial Stout",rank:148}
var A148 = {name:"Bad Boy",brewloc:"Alpine Beer Company",style:"American Double / Imperial IPA",rank:149}
var A149 = {name:"Double Dry Hopped Double Mosaic Daydream",brewloc:"Other Half Brewing Co.",style:"American Double / Imperial IPA",rank:150}
var A150 = {name:"Abraxas",brewloc:"Perennial Artisan Ales",style:"American Double / Imperial Stout",rank:151}
var A151 = {name:"Stickee Monkee",brewloc:"Firestone Walker Brewing Co.",style:"Quadrupel (Quad)",rank:152}
var A152 = {name:"Double Stack",brewloc:"Great Notion Brewing",style:"American Double / Imperial Stout",rank:153}
var A153 = {name:"Hold On To Sunshine",brewloc:"Tree House Brewing Company",style:"Milk / Sweet Stout",rank:154}
var A154 = {name:"Hopslam Ale",brewloc:"Bell's Brewery - Eccentric Café & General Store",style:"American Double / Imperial IPA",rank:155}
var A155 = {name:"Trappist Westvleteren 8 (VIII)",brewloc:"Brouwerij Westvleteren (Sint-Sixtusabdij van Westvleteren)",style:"Dubbel",rank:156}
var A156 = {name:"Barrel-Aged Silhouette",brewloc:"Lift Bridge Brewery",style:"Russian Imperial Stout",rank:157}
var A157 = {name:"St. Bernardus Abt 12",brewloc:"Brouwerij St. Bernardus NV",style:"Quadrupel (Quad)",rank:158}
var A158 = {name:"Maple Bacon Coffee Porter",brewloc:"Funky Buddha Brewery",style:"American Porter",rank:159}
var A159 = {name:"Last Snow",brewloc:"Funky Buddha Brewery",style:"American Porter",rank:160}
var A160 = {name:"Emerald Grouper",brewloc:"Pipeworks Brewing Company",style:"American Double / Imperial IPA",rank:161}
var A161 = {name:"Caffè Americano",brewloc:"Cigar City Brewing",style:"American Double / Imperial Stout",rank:162}
var A162 = {name:"BDCS",brewloc:"Ozark Beer Co.",style:"American Double / Imperial Stout",rank:163}
var A163 = {name:"Bodhi",brewloc:"Columbus Brewing Company",style:"American Double / Imperial IPA",rank:164}
var A164 = {name:"Temptation",brewloc:"Russian River Brewing Company",style:"American Wild Ale",rank:165}
var A165 = {name:"Fuzzy Baby Ducks IPA",brewloc:"New England Brewing Co.",style:"American IPA",rank:166}
var A166 = {name:"Rodenbach Caractère Rouge",brewloc:"Brouwerij Rodenbach N.V.",style:"Flanders Red Ale",rank:167}
var A167 = {name:"Double Dry Hopped All Citra Everything",brewloc:"Other Half Brewing Co.",style:"American Double / Imperial IPA",rank:168}
var A168 = {name:"Aurelian Lure",brewloc:"Jester King Brewery",style:"American Wild Ale",rank:169}
var A169 = {name:"Dragon Fruit Passion Fruit Berliner",brewloc:"J. Wakefield Brewing",style:"Berliner Weissbier",rank:170}
var A170 = {name:"Samuel Adams Utopias",brewloc:"Boston Beer Company (Samuel Adams)",style:"American Strong Ale",rank:171}
var A171 = {name:"Todd The Axe Man India Pale Ale",brewloc:"Surly Brewing Company",style:"American IPA",rank:172}
var A172 = {name:"Barrel-Aged Sump Coffee Stout",brewloc:"Perennial Artisan Ales",style:"American Double / Imperial Stout",rank:173}
var A173 = {name:"Hop JuJu Imperial IPA",brewloc:"Fat Head's Brewery & Saloon",style:"American Double / Imperial IPA",rank:174}
var A174 = {name:"Fort Point Pale Ale",brewloc:"Trillium Brewing Company",style:"American Pale Ale (APA)",rank:175}
var A175 = {name:"Coolship Red",brewloc:"Allagash Brewing Company",style:"Lambic - Fruit",rank:176}
var A176 = {name:"Second Fiddle",brewloc:"Fiddlehead Brewing Company",style:"American Double / Imperial IPA",rank:177}
var A177 = {name:"Imperial Eclipse Stout - Elijah Craig (12 Year)",brewloc:"FiftyFifty Brewing Co.",style:"American Double / Imperial Stout",rank:178}
var A178 = {name:"Bourbon Barrel Champion Ground",brewloc:"Jackie O's Pub & Brewery",style:"American Double / Imperial Stout",rank:179}
var A179 = {name:"Bourbon Barrel Black Maple",brewloc:"Jackie O's Pub & Brewery",style:"American Porter",rank:180}
var A180 = {name:"Trillium / J. Wakefield - Affogato",brewloc:"Trillium Brewing Company",style:"American Double / Imperial Stout",rank:181}
var A181 = {name:"Art",brewloc:"Hill Farmstead Brewery",style:"Saison / Farmhouse Ale",rank:182}
var A182 = {name:"Vicinity",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:183}
var A183 = {name:"Bourbon Barrel Oro Negro",brewloc:"Jackie O's Pub & Brewery",style:"American Double / Imperial Stout",rank:184}
var A184 = {name:"Cantillon Gueuze 100% Lambic",brewloc:"Brasserie Cantillon",style:"Gueuze",rank:185}
var A185 = {name:"Adam From The Wood",brewloc:"Hair Of The Dog Brewing Company / Brewery And Tasting Room",style:"Old Ale",rank:186}
var A186 = {name:"Ghost In The Machine",brewloc:"Parish Brewing Company",style:"American Double / Imperial IPA",rank:187}
var A187 = {name:"Tweak",brewloc:"Avery Brewing Company",style:"American Double / Imperial Stout",rank:188}
var A188 = {name:"Juicy",brewloc:"Hill Farmstead Brewery",style:"Saison / Farmhouse Ale",rank:189}
var A189 = {name:"Fyodor",brewloc:"Stone Brewing",style:"Russian Imperial Stout",rank:190}
var A190 = {name:"Birth Of Tragedy",brewloc:"Hill Farmstead Brewery",style:"American Porter",rank:191}
var A191 = {name:"Hunahpu's Imperial Stout - Bourbon Barrel-Aged",brewloc:"Cigar City Brewing",style:"American Double / Imperial Stout",rank:192}
var A192 = {name:"Mother Of All Storms",brewloc:"Pelican Pub & Brewery",style:"English Barleywine",rank:193}
var A193 = {name:"Sang Noir",brewloc:"Cascade Brewing / Raccoon Lodge & Brewpub",style:"American Wild Ale",rank:194}
var A194 = {name:"Double Nelson",brewloc:"Hill Farmstead Brewery",style:"American Double / Imperial IPA",rank:195}
var A195 = {name:"Oude Geuze Cuvée Armand & Gaston",brewloc:"Brouwerij 3 Fonteinen",style:"Gueuze",rank:196}
var A196 = {name:"La Fosse",brewloc:"Side Project Brewing",style:"American Wild Ale",rank:197}
var A197 = {name:"Damon (Bourbon Barrel Aged)",brewloc:"Hill Farmstead Brewery",style:"Russian Imperial Stout",rank:198}
var A198 = {name:"Nelson",brewloc:"Alpine Beer Company",style:"American IPA",rank:199}
var A199 = {name:"Double Dry Hopped Sleeper Street",brewloc:"Trillium Brewing Company",style:"American IPA",rank:200}
var A200 = {name:"Sante Adairius / Triple Rock Cellarman Barrel Aged Saison",brewloc:"Sante Adairius Rustic Ales",style:"Saison / Farmhouse Ale",rank:201}
var A201 = {name:"Sure Bet",brewloc:"Pipeworks Brewing Company",style:"American Double / Imperial IPA",rank:202}
var A202 = {name:"Kiwi Herman",brewloc:"Alpine Beer Company",style:"American Wild Ale",rank:203}
var A203 = {name:"Citraquench'l",brewloc:"Heist Brewery",style:"American IPA",rank:204}
var A204 = {name:"Clare's Thirsty Ale",brewloc:"Haymarket Beer Co. Pub & Brewery",style:"American Double / Imperial Stout",rank:205}
var A205 = {name:"Epiphany",brewloc:"Foundation Brewing Company",style:"American Double / Imperial IPA",rank:206}
var A206 = {name:"Flora",brewloc:"Hill Farmstead Brewery",style:"Saison / Farmhouse Ale",rank:207}
var A207 = {name:"Coffee Abraxas",brewloc:"Perennial Artisan Ales",style:"American Double / Imperial Stout",rank:208}
var A208 = {name:"Peche 'n Brett",brewloc:"Logsdon Farmhouse Ales",style:"Saison / Farmhouse Ale",rank:209}
var A209 = {name:"Mastermind",brewloc:"Fiddlehead Brewing Company",style:"American Double / Imperial IPA",rank:210}
var A210 = {name:"Edward",brewloc:"Hill Farmstead Brewery",style:"American Pale Ale (APA)",rank:211}
var A211 = {name:"Scaled Up",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:212}
var A212 = {name:"Bourbon Barrel Aged Dark Star",brewloc:"Fremont Brewing Company",style:"Oatmeal Stout",rank:213}
var A213 = {name:"Darkstar November",brewloc:"Bottle Logic Brewing",style:"Russian Imperial Stout",rank:214}
var A214 = {name:"Space Trace",brewloc:"Bottle Logic Brewing",style:"American Double / Imperial Stout",rank:215}
var A215 = {name:"Madagascar",brewloc:"4 Hands Brewing Co.",style:"Milk / Sweet Stout",rank:216}
var A216 = {name:"Enjoy By IPA",brewloc:"Stone Brewing",style:"American Double / Imperial IPA",rank:217}
var A217 = {name:"Locust Reign",brewloc:"New England Brewing Co.",style:"American Double / Imperial IPA",rank:218}
var A218 = {name:"Speedway Stout - Jamaica Blue Mountain Coffee",brewloc:"AleSmith Brewing Company",style:"American Double / Imperial Stout",rank:219}
var A219 = {name:"Sump Coffee Stout",brewloc:"Perennial Artisan Ales",style:"American Double / Imperial Stout",rank:220}
var A220 = {name:"Uncle Jacob's Stout",brewloc:"Avery Brewing Company",style:"American Double / Imperial Stout",rank:221}
var A221 = {name:"Matt",brewloc:"Hair Of The Dog Brewing Company / Brewery And Tasting Room",style:"American Strong Ale",rank:222}
var A222 = {name:"Double Orange Starfish",brewloc:"Aslin Beer Company",style:"American Double / Imperial IPA",rank:223}
var A223 = {name:"Weihenstephaner Hefeweissbier",brewloc:"Bayerische Staatsbrauerei Weihenstephan",style:"Hefeweizen",rank:224}
var A224 = {name:"Framboise For A Cure",brewloc:"Russian River Brewing Company",style:"American Wild Ale",rank:225}
var A225 = {name:"Dialed In (w/ Sauvignon Blanc Juice)",brewloc:"Trillium Brewing Company",style:"American Double / Imperial IPA",rank:226}
var A226 = {name:"Citra Pale Ale",brewloc:"Hill Farmstead Brewery",style:"American Pale Ale (APA)",rank:227}
var A227 = {name:"Péché Mortel",brewloc:"Brasserie Dieu du Ciel!",style:"American Double / Imperial Stout",rank:228}
var A228 = {name:"Péché Mortel - Fût De Bourbon Américain",brewloc:"Brasserie Dieu du Ciel!",style:"American Double / Imperial Stout",rank:229}
var A229 = {name:"M-43 N.E. India Pale Ale",brewloc:"Old Nation Brewing Co.",style:"American IPA",rank:230}
var A230 = {name:"Hop Venom Double IPA",brewloc:"Boneyard Beer Company",style:"American Double / Imperial IPA",rank:231}
var A231 = {name:"Cantillon Vigneronne",brewloc:"Brasserie Cantillon",style:"Lambic - Fruit",rank:232}
var A232 = {name:"Coolship Resurgam",brewloc:"Allagash Brewing Company",style:"American Wild Ale",rank:233}
var A233 = {name:"Double Dry Hopped Scaled",brewloc:"Trillium Brewing Company",style:"American IPA",rank:234}
var A234 = {name:"B-Bomb (Bourbon Abominable Winter Ale)",brewloc:"Fremont Brewing Company",style:"American Strong Ale",rank:235}
var A235 = {name:"Oude Tart - Cherries",brewloc:"Bruery Terreux",style:"American Wild Ale",rank:236}
var A236 = {name:"Trickery",brewloc:"Hardywood Park Craft Brewery",style:"Milk / Sweet Stout",rank:237}
var A237 = {name:"Mélange No. 3",brewloc:"The Bruery",style:"American Strong Ale",rank:238}
var A238 = {name:"Barrel Aged Double Shot Double Black",brewloc:"Bent Paddle Brewing Co.",style:"American Black Ale",rank:239}
var A239 = {name:"Yellow Rose",brewloc:"The Lone Pint Brewery",style:"American IPA",rank:240}
var A240 = {name:"Rue D'Floyd",brewloc:"The Bruery",style:"American Porter",rank:241}
var A241 = {name:"Dreadnaught IPA",brewloc:"3 Floyds Brewing Co.",style:"American Double / Imperial IPA",rank:242}
var A242 = {name:"Leon",brewloc:"Cigar City Brewing",style:"English Barleywine",rank:243}
var A243 = {name:"Citra Showers",brewloc:"Noble Ale Works",style:"American Double / Imperial IPA",rank:244}
var A244 = {name:"Master Of Karate",brewloc:"Aslin Beer Company",style:"American Double / Imperial IPA",rank:245}
var A245 = {name:"Oro Negro",brewloc:"Jackie O's Pub & Brewery",style:"American Double / Imperial Stout",rank:246}
var A246 = {name:"Mexican Cake",brewloc:"Westbrook Brewing Co.",style:"American Double / Imperial Stout",rank:247}
var A247 = {name:"Drie Fonteinen Oude Geuze",brewloc:"Brouwerij 3 Fonteinen",style:"Gueuze",rank:248}
var A248 = {name:"Kentucky Christmas Morning",brewloc:"Hardywood Park Craft Brewery",style:"Milk / Sweet Stout",rank:249}
var A249 = {name:"Softly Spoken Magic Spells",brewloc:"SingleCut Beersmiths",style:"American Double / Imperial IPA",rank:250}

var data = [A0,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21,A22,A23,A24,A25,A26,A27,A28,A29,A30,A31,A32,A33,A34,A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,A46,A47,A48,A49,A50,A51,A52,A53,A54,A55,A56,A57,A58,A59,A60,A61,A62,A63,A64,A65,A66,A67,A68,A69,A70,A71,A72,A73,A74,A75,A76,A77,A78,A79,A80,A81,A82,A83,A84,A85,A86,A87,A88,A89,A90,A91,A92,A93,A94,A95,A96,A97,A98,A99,A100,A101,A102,A103,A104,A105,A106,A107,A108,A109,A110,A111,A112,A113,A114,A115,A116,A117,A118,A119,A120,A121,A122,A123,A124,A125,A126,A127,A128,A129,A130,A131,A132,A133,A134,A135,A136,A137,A138,A139,A140,A141,A142,A143,A144,A145,A146,A147,A148,A149,A150,A151,A152,A153,A154,A155,A156,A157,A158,A159,A160,A161,A162,A163,A164,A165,A166,A167,A168,A169,A170,A171,A172,A173,A174,A175,A176,A177,A178,A179,A180,A181,A182,A183,A184,A185,A186,A187,A188,A189,A190,A191,A192,A193,A194,A195,A196,A197,A198,A199,A200,A201,A202,A203,A204,A205,A206,A207,A208,A209,A210,A211,A212,A213,A214,A215,A216,A217,A218,A219,A220,A221,A222,A223,A224,A225,A226,A227,A228,A229,A230,A231,A232,A233,A234,A235,A236,A237,A238,A239,A240,A241,A242,A243,A244,A245,A246,A247,A248,A249]